config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :roles

  map.devise_for :users
  map.resources :users

  map.resources :gamegeneres

  map.edit_discs '/contents/:id/edit_discs', :controller => 'contents', :action => 'edit_discs'
  map.resources :contents

  map.resources :moviegeneres

  map.resources :contentcategories

  map.resources :contenttypes

  map.resources :disctypes

  map.search_discs 'discs/search', :controller => 'discs', :action => 'search'
  map.resources :discs

  map.resources :containers

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  map.root :controller => 'application', :action => 'index'
end

app/models/container.rb
# == Schema Information
# Schema version: 15
#
# Table name: containers
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Container < ActiveRecord::Base
  attr_accessible :name, :description
  
  has_many :discs
end

app/models/content.rb
# == Schema Information
# Schema version: 15
#
# Table name: contents
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  contenttype_id     :integer
#  gamegenere_id      :integer
#  contentcategory_id :integer
#  cracked            :boolean
#  original           :boolean
#  moviegenere_id     :integer
#  moviequality       :string(255)
#  movieyear          :integer
#  subtitules         :string(255)
#  comment            :text
#  created_at         :datetime
#  updated_at         :datetime
#  date               :datetime
#  language           :string(255)
#

class Content < ActiveRecord::Base
  attr_accessible :name, :contenttype_id, :gamegenere_id, :contentcategory_id, :disc_ids, :cracked, :original, :moviegenere_id, :moviequality, :movieyear, :subtitules, :comment, :language

  belongs_to :contenttype
  belongs_to :contentcategory
  belongs_to :gamegenere
  has_many :disc_contents
  has_many :discs, :through => :disc_contents
  belongs_to :moviegenere
end

app/models/contenttype.rb
# == Schema Information
# Schema version: 15
#
# Table name: contenttypes
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Contenttype < ActiveRecord::Base
  attr_accessible :name, :description
  
  has_many :contents
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(params[:content])
    if @content.save
      flash[:notice] = "Successfully created content."
      redirect_to new_content_path
    else
      render :action => 'new'
    end
  end

  def edit_discs
    @content = Content.find_by_id params[:id]
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update_attributes(params[:content])
      flash[:notice] = "Successfully updated content."
      redirect_to @content
    else
      render :action => 'edit'
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    flash[:notice] = "Successfully destroyed content."
    redirect_to contents_url
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_discs_form.html.erb
<% semantic_form_for @content do |f| %>
  <%= f.error_messages %>
  <% f.inputs do %>
    <%= f.input :discs, :as => :check_boxes, :collection => Disc.all %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/contents/_form.html.erb
<% semantic_form_for @content do |f| %>
  <%= f.error_messages %>
  <%= f.inputs %>
  <% f.inputs do %>
    <%= f.input :discs, :as => :check_boxes, :collection => Disc.all.select{|d| d.content_ids.empty? or d.label == 'Juegos Varios'} %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/contents/edit.html.erb
<% title "Edit Content" %>

<%= render :partial => 'form' %>

<%= common_links :section => :edit_discs, :object => @content %>

app/views/contents/edit_discs.html.erb
<% title "Edit Discs Content" %>

<%= render :partial => 'discs_form' %>

<%= common_links :section => :show, :object => @content %>

app/views/contents/index.html.erb
<% title "Contents" %>

<table>
  <tr>
    <th>Name</th>
    <th>Contenttype</th>
    <th>Discs</th>
  </tr>
  <% for content in @contents %>
    <tr>
      <td><%=h content.name %></td>
      <td><%=h content.contenttype.name %></td>
      <td><%=h content.disc_ids.empty? ? 'None' : content.discs.collect{|d| d.number}.join(', ') %></td>
      <%= common_links :section => :list, :object => content %>
    </tr>
  <% end %>
</table>
<%= common_links :section => :main, :klass => Content %>

app/views/contents/new.html.erb
<% title "New Content" %>

<%= render :partial => 'form' %>

<%= common_links :section => :new, :object => @content %>

app/views/contents/show.html.erb
<% title "Content" %>

<p>
  <strong>Name:</strong>
  <%=h @content.name %>
</p>
<p>
  <strong>Contenttype:</strong>
  <%=h @content.contenttype_id.nil? ? 'N/A' : @content.contenttype.name %>
</p>
<p>
  <strong>Discs:</strong>
  <% if @content.disc_ids.empty? %>
    'N/A'
  <% else %>
    <ul>
      <% @content.discs.each do |disc| %>
        <li><%=h [disc.container.name, disc.number, disc.label].join(' - ')%></li>
      <% end %>
    </ul>
  <% end %>
</p>
<p>
  <strong>Gamegenere:</strong>
  <%=h @content.gamegenere_id.nil? ? 'N/A' : @content.gamegenere.name %>
</p>
<p>
  <strong>Contentcategory:</strong>
  <%=h @content.contentcategory_id.nil? ? 'N/A' : @content.contentcategory.name %>
</p>
<p>
  <strong>Cracked:</strong>
  <%=h @content.cracked %>
</p>
<p>
  <strong>Original:</strong>
  <%=h @content.original %>
</p>
<p>
  <strong>Moviegenere:</strong>
  <%=h @content.moviegenere_id.nil? ? 'N/A' : @content.moviegenere.name %>
</p>
<p>
  <strong>Moviequality:</strong>
  <%=h @content.moviequality.nil? ? 'N/A' : @content.moviequality %>
</p>
<p>
  <strong>Movieyear:</strong>
  <%=h @content.movieyear.nil? ? 'N/A' : @content.movieyear %>
</p>
<p>
  <strong>Language:</strong>
  <%=h @content.language.nil? ? 'N/A' : @content.language %>
</p>
<p>
  <strong>Subtitules:</strong>
  <%=h @content.subtitules.nil? ? 'N/A' : @content.subtitules %>
</p>
<p>
  <strong>Comment:</strong><br/>
  <pre><%=h @content.comment %></pre>
</p>

<%= common_links :section => :edit_discs, :object => @content %>